<?php

declare(strict_types=1);

namespace BtcPayLite;

final class ApplicationRouter
{
    /**
     * @var array<string,array{methods:list<string>,handler?:string,menu?:string,role?:string,redirect?:string}>
     */
    private array $routes;

    public function __construct()
    {
        $this->routes = [
            '/' => $this->page(['GET', 'HEAD'], 'pages/prezentace.php', 'home'),
            '/home' => $this->redirect('/'),
            '/prezentace' => $this->redirect('/'),
            '/dokumentace' => $this->page(['GET', 'HEAD'], 'pages/dokumentace.php', 'dokumentace'),
            '/login' => $this->page(['GET', 'HEAD', 'POST'], 'client/login.php', 'login'),
            '/forgot-password' => $this->page(
                ['GET', 'HEAD', 'POST'], 'client/forgot_password.php', 'forgot_password'
            ),
            '/reset-password' => $this->page(
                ['GET', 'HEAD', 'POST'], 'client/reset_password.php', 'reset_password'
            ),
            '/registrace' => $this->page(['GET', 'HEAD', 'POST'], 'client/registrace.php', 'registrace'),
            '/registrace.php' => $this->redirect('/registrace'),
            '/client' => $this->page(['GET', 'HEAD', 'POST'], 'client/index.php', 'client', 'client'),
            '/client/account' => $this->page(
                ['GET', 'HEAD', 'POST'], 'pages/account.php', 'account', 'client'
            ),
            '/dashboard' => $this->redirect('/client'),
            '/api' => $this->page(['POST'], 'api_stateless.php', 'api'),
            '/api/stateless/invoices' => $this->page(
                ['POST'], 'api_stateless.php', 'api'
            ),
            '/pay' => $this->page(['GET', 'HEAD'], 'checkout/pay.php', 'pay'),
            '/url-invoice' => $this->page(
                ['GET', 'HEAD'], 'admin/url_pay.php', 'url_invoice'
            ),
            // Backwards-compatible aliases for links generated by older builds.
            '/url_pay' => $this->page(
                ['GET', 'HEAD'], 'admin/url_pay.php', 'url_invoice'
            ),
            '/admin/url_pay' => $this->page(
                ['GET', 'HEAD'], 'admin/url_pay.php', 'url_invoice'
            ),
            '/admin' => $this->redirect('/admin/dashboard'),
            '/admin/dashboard' => $this->page(
                ['GET', 'HEAD'], 'admin/dashboard.php', 'dashboard', 'admin'
            ),
            '/admin/account' => $this->page(
                ['GET', 'HEAD', 'POST'], 'pages/account.php', 'account', 'admin'
            ),
            '/admin/users' => $this->page(
                ['GET', 'HEAD', 'POST'], 'admin/users.php', 'users', 'admin'
            ),
            '/admin/settings' => $this->page(
                ['GET', 'HEAD', 'POST'], 'admin/settings.php', 'settings', 'admin'
            ),
            '/admin/wallet' => $this->page(
                ['GET', 'HEAD', 'POST'], 'admin/wallet.php', 'wallet', 'admin'
            ),
            '/admin/stores' => $this->page(
                ['GET', 'HEAD', 'POST'], 'admin/stores.php', 'stores', 'admin'
            ),
            '/admin/invoices' => $this->page(
                ['GET', 'HEAD', 'POST'], 'admin/invoices.php', 'invoices', 'admin'
            ),
            '/admin/webhooks' => $this->page(
                ['GET', 'HEAD', 'POST'], 'admin/webhooks.php', 'webhooks', 'admin'
            ),
            '/admin/url_invoices' => $this->page(
                ['GET', 'HEAD', 'POST'], 'admin/url_invoices.php', 'url_invoices', 'admin'
            ),
        ];
    }

    public function match(string $path, string $method): ApplicationRoute
    {
        $definition = $this->routes[$path] ?? null;
        if ($definition === null) {
            throw new RouterException('Page not found.', 404);
        }

        $method = strtoupper($method);
        if (!in_array($method, $definition['methods'], true)) {
            throw new RouterException('Method is not allowed for this route.', 405, $definition['methods']);
        }

        if (isset($definition['redirect'])) {
            return ApplicationRoute::redirect($definition['redirect']);
        }

        return ApplicationRoute::handler(
            $definition['handler'],
            $definition['menu'],
            $definition['role'] ?? null
        );
    }

    /**
     * @param list<string> $methods
     * @return array{methods:list<string>,handler:string,menu:string,role?:string}
     */
    private function page(array $methods, string $handler, string $menu, ?string $role = null): array
    {
        $route = ['methods' => $methods, 'handler' => $handler, 'menu' => $menu];
        if ($role !== null) {
            $route['role'] = $role;
        }
        return $route;
    }

    /** @return array{methods:list<string>,redirect:string} */
    private function redirect(string $path): array
    {
        return ['methods' => ['GET', 'HEAD'], 'redirect' => $path];
    }
}
